name: main-android

on: workflow_dispatch

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
        name: Android
        os: ubuntu-22.04
        buildArgs: "android"
        artifactName: android-AFUS
        artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
